name: Expressions test

on: workflow_dispatch

env:
  myBoolean: ${{ false }}
  myIntegerNumber: ${{ 711 }}

jobs:
  Test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Prints number value from env variable
        run: echo "This is my number value ==> $myIntegerNumber"
        
      - name: Skipped step
        run: echo "You will not see this message"
        if: ${{ env.myBoolean }}

      - name: Env value accessed before execution
        run: echo "This is my boolean value ==> ${{ env.myBoolean }}"
        
      - name: Env value accessed at the time of execution
        run: echo "This is my boolean value ==> ${{ $myBoolean }}"
