name: Test GH Action file

on:
  create:

jobs:
  logs-on-console:
    runs-on: ubuntu-latest
    steps:
      - name: Log 001
        run: echo 'Hello World 👋'
        
      - name: Log 002
        run: echo 'Bye 🙋‍♂️'
