name: PRs reviews reminder

on:
  pull_request:
    types: [opened, reopened]
  schedule:
    # Every weekday at 9-18 every hour, send notification
    - cron: "0 9-18/1 * * 1-5"

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.23.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: 'C02JH3BRPAA'
        # For posting a simple plain text message
        slack-message: "A PR is open: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: "Payoneer's Github Actions"
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}`