name: Slack Pull Request Open Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Normal text
      run: echo "This step will always run"
    - name: Dynamic value
      run: echo "Open PR ${{ github.event.pull_request.html_url }} ${{ github.event.pull_request.created_at }}"
