name: Slack notification with webhook (Simplified)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  schedule:
    # Every weekday at 9-18 every hour, send notification
    - cron: "*/1 * * * *"

jobs:
  Slack-Webhook:
    runs-on: ubuntu-latest
    steps:  
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "An opened PR needs your attention"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n <${{ github.repositoryUrl }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered by:*\n ${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Open PR:*\n ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
